CREATE TABLE IF NOT EXISTS foods (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  price INTEGER,
  image TEXT,
  tags TEXT
);

CREATE TABLE IF NOT EXISTS meal_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL,
  food_ids TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_checkins (
  date TEXT PRIMARY KEY,
  status TEXT NOT NULL CHECK (status IN ('FOLLOWED', 'NOT_FOLLOWED'))
);
